#+AUTHOR: Панков Вася
#+latex_header: \usepackage[utf8x]{inputenc}
#+latex_header: \usepackage[T2A]{fontenc}
#+latex_header: \usepackage[russian,english]{babel}
#+TITLE: Социальная адаптация

* Планы
  :PROPERTIES:
  :CUSTOM_ID: социальная-адаптация
  :END:
*4 проекта* (-ика):

1. Презентация "Успешная история людей с ОВС" (до 15 февраля) 1 слайд -
   Фотография + даты жизни 2 слайд - Заболевание врождённое и
   приобретённое 3 слайд - Суть проблемы(заболевания), статистика 4
   слайд - Чудо 5 слайд - Наследие 6 слайд - Спасибо за внимание

2. 'Научная' статья (с 15 февраля до 15 марта) !*Автор* !*Место
   обучения* !*УДК*(универсальный десятичный код) !*Аннотация*
   !*Ключевые слова*(5) !*Тема* (Социальные факторы адаптации людей с
   /.../)(Как у презентации) !* Перевод на английский* (SUAI) !*Два
   абзаца по 5 строчек* !*Список используемых ресурсов*(1 книжка, 1
   сайт)

3. Профессиограмма (с 15 марта по 15 апреля)

4. Пройти проф. тестирование, написать отчёт(с 15 апреля по 15 мая)

* Введение
   :PROPERTIES:
   :CUSTOM_ID: введение
   :END:
Раньше:

Была мед. модель людей с ОВЗ - отдельная система заведений(школы, сады и
тп...) и пособия.

С 2009 года:

/Экономика:/

- /производство/

- /распределение/

- /сбыт/

- /обмен/

- /потребление/

В связи цифровой экономикой у инвалидов появилось больше возможностей.

!*Чем выше уровень экономики государства, чем выше уровень медицины, тем
больше людей с инвалидностью.* Идея в том, что снижается естественный
отбор.\\
Человечество увеличивает продолжительность жизни, но при этом
увеличивается количество болезней.

*Моя тема:* Майкл Джей Фокс.

 

Социальная модель (трудоустройство инвалидов), инвалидов интергрирует в
общество.

Инклюзивное образование.

 

Итак,

| 2030           | Цифровая экономика | Инвалиды получабт пособие | В обществе растёт гуманизм |
|----------------+--------------------+---------------------------+----------------------------|
| Рост экономика | Медицина           | Растёт число людей с ОВЗ  | Что делать? Инклюзия       |

С 2013 года работает программа "Доступная среда"

!! Ч. Дарвин: "Выживает не сильнейший, не умнейший, а тот кто умеет
адаптироваться"

 

* 4 Модели жизни
   :PROPERTIES:
   :CUSTOM_ID: модели-жизни
   :END:
4 модели жизни:

- Холерик - очень сильная нервная система, преобладает возбуждение,
  быстрая, хаотичная речь.\\
  Любовь холерика: очень влюбчивый. Со временем, любовь как ценность
  убивает. Измены. Любовь это достижение целей. Брак

  - так получилось.\\
    Любовь к детям это деньги, гаджеты, что-то матеръяльное. Обращают на
    детей, только когда проблем, главнаая функция
    - защита.\\
      Друзья: куча знакомых, очень много связей. Нужные люди.\\
      Ценности: дело, работа, деньги, свобода.\\
      Работа: везде, но начальником.(предпринимательство) Холерик не
      любит не на кого работать, быстрый карьерный рост. Бесят
      расписания.\\
      Одежда: от природы холерик-лидер, обожает яркое, модное.\\
      Риски - много переживает и проблемы с сердцем

- Меланхолик - нет реакции на окружающий мир, Речь: тихая, тактичная
  речь. Его никто не слышит. Общается с единицыми. Разговаривает сам с
  собой и читает. Любовь: это смысл его жизни, это то ради чего он
  живёт, однолюбы, но очень влюбчивые. Нет пола, возраста и тп.\\
  Дети: нет или 1\\
  Друзья - только духовные\\
  Ценности: любовь и творчество\\
  Работа: любая, но без людей, любая творческая профессия\\
  Одежда: должна о нём рассказывать, романтичная одежда\\
  Риски: вся психическая сфера

- Сангвиники - адекватное торможение и возбуждение (уравновешенность)
  Высокая адаптивность. Речь: он подстраивается под собеседника. Он
  никогда не конфликтует. Нет барьеров в общении. Любовь: меньше всего
  разводов и страсти нет, живут ради детей, брак = дружба. Влюбчивые, но
  могут остановиться. Постоянно уходят во флирт. С бывшими дружат.
  Дети - они сами дети, с детьми дружат. Друзья - это смысл жизни.
  Ценности: то чем можно манипулировать. Работа: психолог, консультант,
  учитель... Одежда: под настроение. Риски: умереть от старости

- Флегматик - преобладает торможение. Речь - медленная(эээ...),
  ненавидит повторы. Не проявляют эмоции. Любовь - мужчина(есть хорошо -
  нету не надо) женщины(дети!!!). Дети - наследие. Друзья: всё меньше и
  меньше и друзья превращаются в коллег на работе. Фишка:
  родители(особенно мама), тщеславие, деньги(он не жмот, а жмот
  дальновидный). Работа: психоаналитика, программист(тестировщик), любой
  инженер. Одежда: что-то прагматичное(не любит менять одежду) ” я не
  дурак и не настолько богат, чтобы покупать дешёвые вещи”

Совместимость сангвиника:

С - С = Всё прекрасно, но жизнь скучная

С - Ф = Сангвиник должен быть старше

С - Х = Идеальная пара

С - М = Недолгие отношения

Совместимость Холерика:

Х - Х = Хорошая пара, но если они отдыхают друг от друга

Х - Ф = Борьба за власть и деньги

Х - М

* Восемь кризисов жизни
   :PROPERTIES:
   :CUSTOM_ID: восемь-кризисов-жизни
   :END:
1. 0 - 1 года - кризис рождения
   1. Эмоциональный фон(от мамы, в основном)
   2. Пессимизм или оптимизм
2. 1 - 3 года - кризис деятельности
   - Конец кризиса, когда в речи появляются местоимения
   - Формирование лобных долей
3. 3 - 6 лет - кризис эго
   - Формирование морали
   - Sex-табу, до 5 лет привлечение с родителем противоположного
     возраста
   - Эдипов комплекс или Комплексе Электра(необъяснимая любовь девочки к
     отцу)
   - Почемучка(бесконечный допрос)
4. 6 - 12 лет - интеллект
   - Инициатива(хотят помогать) -> не ругать
   - Профессиональная ориентация
5. 12 - 19 лет - Подростковый
   - Гормоны
   - Аффекты
   - Первая любовь - нужна чтобы страдать(влюбиться в того, с кем быть
     не можешь), плотоническая любовь, суицидные мысли
   - Полорелевая id
     - Мужчины
       - Юношенский максимализм(подвиги и испытания)
       - Мужская самооценка(выполнил много дел)
     - Женщины
       - Внутренний конфликт
       - Женская самооценка
6. 20 - 25 лет - Кризис интимности
   - Умение проникнуть не только в тело, но и в душу
   - Период формирования серьёзных отношений
     - первый социальный опыт
       - Мужчины - успешные
       - Женщины - красивая
7. 25 – 40 лет - Кризис среднего возраста  
  У мужчин длиннее детородный период 
	Желание сломать свою жизнь:
	- заводят любовницу на работе
	- вредные привычки
	+ написать заявление об уходе
	+ нов	
  У женщин детородный период заканчивается примерно в 45
 - 40 - 45 лет
  - молодая любовница
  - вредные привычки
  - конкуренция с молодыми
  + шопинг
  + диета спорт
  У женщины гормональный бум 30 – 36 
  - Я умная
    Плюсы:
    - 2 образование
    - смена работы и тд.
    Минусы:
    - может сменить партнёра
    - плохие привычки
  - Я красивая
    Плюсы
    - рождение детей
    - заняться красотой
    Минусы
    - может сменить партнёра
    - вредные привычки

 8. 45 - ??? лет Сворачивание +шеи+ жизни
    Страх смерти:
    - Есть - жизнь прожита зря
    - Нет - жизнь прожита как хотел(жизнь удалась)

