#+TITLE: ЛАБОРАТОРНАЯ РАБОТА №18. Права доступа в Ubuntu.
#+AUTHOR: Панков Вася

Цель работы: ознакомиться с работой команды по изменению прав доступа.

1. Порядок выполнения работы.
   1. Войдите в систему как системный пользователь (не root).
      
   2. Ознакомиться с процедурами входа в систему,
      выполнения основных команд, получения подсказки,
      создания и редактирования текстовых файлов.

   3. Изучить команды изменения прав доступа и владения chmod и chown.

   4. Выполнить указанные в задании действия над каталогами, файлами, ссылками.

   5. Провести изменения прав доступа к файлам и каталогам.

      1. Открыть для своей группы доступ к своему домашнему каталогу для чтения и записи.

   6. Создайте в своем домашнем каталоге новый каталог с именем "свой пользователь"_lab, например, zaitsev_lab, перейдите в него.

      1. Создайте один каталог с произвольным именем (напр. tmp), перейдите в него.
      2. Создайте два файла с произвольными именами.
      3. Присвойте одному файлу права на исполнение только для текущего пользовате-ля; присвойте второму файлу права только на чтение и запись для пользователя и группы. Сделайте скриншот команды ls –l.
      4. Перейдите в начальный каталог (zaitsev_lab). Удалите права на исполнение для каталога tmp.
      5. Сделайте скриншот команд cd tmp и ls –l tmp. Объясните результаты команд.
      6. Разрешите права на исполнение каталогу tmp.
	 Проверьте текущие права на фай-лы.
	 Назначьте права на файлы, указанные в вашем варианте в числовом виде, в бук-венном представлении относительно текущих прав, используя добавление, удаление или назначение прав.
	 Например: 777 – +rwx, т.е. chmod ugo+wrx file.
	 Сделайте скриншот результатов этой команды.
      7. Объясните следующие значения прав на каталог: 700, 755, 777.
2. Контрольные вопросы.
   1. Команды chmod и chown. Назначение и применение.

   2. Отличия между правами на файл и на директорию.

   3. 13 вариант - 040
