#+AUTHOR: Панков Вася
#+latex_header: \usepackage[utf8x]{inputenc}
#+latex_header: \usepackage[T2A]{fontenc}
#+latex_header: \usepackage[russian,english]{babel}
#+TITLE: Социальная адаптация

* Планы
  :PROPERTIES:
  :CUSTOM_ID: социальная-адаптация
  :END:
*4 проекта* (-ика):

1. Презентация "Успешная история людей с ОВС" (до 15 февраля) 1 слайд -
   Фотография + даты жизни 2 слайд - Заболевание врождённое и
   приобретённое 3 слайд - Суть проблемы(заболевания), статистика 4
   слайд - Чудо 5 слайд - Наследие 6 слайд - Спасибо за внимание

2. 'Научная' статья (с 15 февраля до 15 марта) !*Автор* !*Место
   обучения* !*УДК*(универсальный десятичный код) !*Аннотация*
   !*Ключевые слова*(5) !*Тема* (Социальные факторы адаптации людей с
   /.../)(Как у презентации) !* Перевод на английский* (SUAI) !*Два
   абзаца по 5 строчек* !*Список используемых ресурсов*(1 книжка, 1
   сайт)

3. Профессиограмма (с 15 марта по 15 апреля)

4. Пройти проф. тестирование, написать отчёт(с 15 апреля по 15 мая)

* Введение
   :PROPERTIES:
   :CUSTOM_ID: введение
   :END:
Раньше:

Была мед. модель людей с ОВЗ - отдельная система заведений(школы, сады и
тп...) и пособия.

С 2009 года:

/Экономика:/

- /производство/

- /распределение/

- /сбыт/

- /обмен/

- /потребление/

В связи цифровой экономикой у инвалидов появилось больше возможностей.

!*Чем выше уровень экономики государства, чем выше уровень медицины, тем
больше людей с инвалидностью.* Идея в том, что снижается естественный
отбор.\\
Человечество увеличивает продолжительность жизни, но при этом
увеличивается количество болезней.

*Моя тема:* Майкл Джей Фокс.

 

Социальная модель (трудоустройство инвалидов), инвалидов интергрирует в
общество.

Инклюзивное образование.

 

Итак,

| 2030           | Цифровая экономика | Инвалиды получабт пособие | В обществе растёт гуманизм |
|----------------+--------------------+---------------------------+----------------------------|
| Рост экономика | Медицина           | Растёт число людей с ОВЗ  | Что делать? Инклюзия       |

С 2013 года работает программа "Доступная среда"

!! Ч. Дарвин: "Выживает не сильнейший, не умнейший, а тот кто умеет
адаптироваться"

 

* 4 Модели жизни (Темперамент)
   :PROPERTIES:
   :CUSTOM_ID: модели-жизни
   :END:
4 модели жизни:

- Холерик - очень сильная нервная система, преобладает возбуждение,
  быстрая, хаотичная речь.\\
  Любовь холерика: очень влюбчивый. Со временем, любовь как ценность
  убивает. Измены. Любовь это достижение целей. Брак

  - так получилось.\\
    Любовь к детям это деньги, гаджеты, что-то матеръяльное. Обращают на
    детей, только когда проблем, главнаая функция
    - защита.\\
      Друзья: куча знакомых, очень много связей. Нужные люди.\\
      Ценности: дело, работа, деньги, свобода.\\
      Работа: везде, но начальником.(предпринимательство) Холерик не
      любит не на кого работать, быстрый карьерный рост. Бесят
      расписания.\\
      Одежда: от природы холерик-лидер, обожает яркое, модное.\\
      Риски - много переживает и проблемы с сердцем

- Меланхолик - нет реакции на окружающий мир, Речь: тихая, тактичная
  речь. Его никто не слышит. Общается с единицыми. Разговаривает сам с
  собой и читает. Любовь: это смысл его жизни, это то ради чего он
  живёт, однолюбы, но очень влюбчивые. Нет пола, возраста и тп.\\
  Дети: нет или 1\\
  Друзья - только духовные\\
  Ценности: любовь и творчество\\
  Работа: любая, но без людей, любая творческая профессия\\
  Одежда: должна о нём рассказывать, романтичная одежда\\
  Риски: вся психическая сфера

- Сангвиники - адекватное торможение и возбуждение (уравновешенность)
  Высокая адаптивность. Речь: он подстраивается под собеседника. Он
  никогда не конфликтует. Нет барьеров в общении. Любовь: меньше всего
  разводов и страсти нет, живут ради детей, брак = дружба. Влюбчивые, но
  могут остановиться. Постоянно уходят во флирт. С бывшими дружат.
  Дети - они сами дети, с детьми дружат. Друзья - это смысл жизни.
  Ценности: то чем можно манипулировать. Работа: психолог, консультант,
  учитель... Одежда: под настроение. Риски: умереть от старости

- Флегматик - преобладает торможение. Речь - медленная(эээ...),
  ненавидит повторы. Не проявляют эмоции. Любовь - мужчина(есть хорошо -
  нету не надо) женщины(дети!!!). Дети - наследие. Друзья: всё меньше и
  меньше и друзья превращаются в коллег на работе. Фишка:
  родители(особенно мама), тщеславие, деньги(он не жмот, а жмот
  дальновидный). Работа: психоаналитика, программист(тестировщик), любой
  инженер. Одежда: что-то прагматичное(не любит менять одежду) ” я не
  дурак и не настолько богат, чтобы покупать дешёвые вещи”

Совместимость сангвиника:

С - С = Всё прекрасно, но жизнь скучная

С - Ф = Сангвиник должен быть старше

С - Х = Идеальная пара

С - М = Недолгие отношения

Совместимость Холерика:

Х - Х = Хорошая пара, но если они отдыхают друг от друга

Х - Ф = Борьба за власть и деньги

Х - М = Точно нет, есть только один вариант - если холерик садист а меланхолик мазохист (Преследователь и жертва)

Совместимость флегматик:

Ф - Ф = обьединяет работа

Ф - М = Флегматик мальчик, серьезный, девочка меланхолик

Совместимость меланхолик:

М - М = всегда совместимы

* Восемь кризисов жизни
   :PROPERTIES:
   :CUSTOM_ID: восемь-кризисов-жизни
   :END:
1. 0 - 1 года - кризис рождения
   1. Эмоциональный фон(от мамы, в основном)
   2. Пессимизм или оптимизм
2. 1 - 3 года - кризис деятельности
   - Конец кризиса, когда в речи появляются местоимения
   - Формирование лобных долей
3. 3 - 6 лет - кризис эго
   - Формирование морали
   - Sex-табу, до 5 лет привлечение с родителем противоположного
     возраста
   - Эдипов комплекс или Комплексе Электра(необъяснимая любовь девочки к
     отцу)
   - Почемучка(бесконечный допрос)
4. 6 - 12 лет - интеллект
   - Инициатива(хотят помогать) -> не ругать
   - Профессиональная ориентация
5. 12 - 19 лет - Подростковый
   - Гормоны
   - Аффекты
   - Первая любовь - нужна чтобы страдать(влюбиться в того, с кем быть
     не можешь), плотоническая любовь, суицидные мысли
   - Полорелевая id
     - Мужчины
       - Юношенский максимализм(подвиги и испытания)
       - Мужская самооценка(выполнил много дел)
     - Женщины
       - Внутренний конфликт
       - Женская самооценка
6. 20 - 25 лет - Кризис интимности
   - Умение проникнуть не только в тело, но и в душу
   - Период формирования серьёзных отношений
     - первый социальный опыт
       - Мужчины - успешные
       - Женщины - красивая
7. 25 – 40 лет - Кризис среднего возраста  
  У мужчин длиннее детородный период 
	Желание сломать свою жизнь:
	- заводят любовницу на работе
	- вредные привычки
	+ написать заявление об уходе
	+ нов	
  У женщин детородный период заканчивается примерно в 45
 - 40 - 45 лет
  - молодая любовница
  - вредные привычки
  - конкуренция с молодыми
  + шопинг
  + диета спорт
  У женщины гормональный бум 30 – 36 
  - Я умная
    Плюсы:
    - 2 образование
    - смена работы и тд.
    Минусы:
    - может сменить партнёра
    - плохие привычки
  - Я красивая
    Плюсы
    - рождение детей
    - заняться красотой
    Минусы
    - может сменить партнёра
    - вредные привычки

 8. 45 - ??? лет Сворачивание +шеи+ жизни
    Страх смерти:
    - Есть - жизнь прожита зря
    - Нет - жизнь прожита как хотел(жизнь удалась)

* Интеллект
Норма айкью - 100 
IQ > 100: 2 варианта - человек учится на все пятерки (всезнайки) - их беда в том что они распыляются на все, 
2 вариант: гении в какой-то области. Либо в вербальной либо в математической логике они круче.

IQ = 90 - ЗПР задержка психического развития. Бывает двух разных видов:
1. ЗПР
2. Эмоционально-волевой инфанрелизм

IQ = 80 - легкая дебильность

IQ = 70 - средняя дебильность

(!) - Легкие и средние дебилы дееспособны.

Черта означает окончание человеческого мира, начало звериного

IQ = 60 - имбециллы (высшие животные, дрессируемые и обучаемые)

IQ = 50 - идиот (необучаем, функция есть пить и размножаться)

ОНИ НЕДЕЕСПОСОБНЫ

Эти люди могут учиться: 
1. обычная школа/инклюзивное образование 
2. Уйти в домашнее обучение 
3. Дистанционное обучение в школе 
4. Коррекционные школы или классы (Такая школа идет 12 лет, получают образование шести классов + профессиональное образование) 
У них очень сильно зашкаливает конкретность мысления. Второй критерий интеллекта: обучаемость.
Интеллект - это когда вы сталкиваетесь с задачей, и вы распределяете их на ограниченное время.

* Гендеры

Зверь(природные) <--> Божественные(социальные)
     ПОЛ                   Гендер
 Дискретность            Не дискретность

Гендер:
- Профессия
  - Программирование и шахматы(пока ещё) удел мужчин
- Одежда
- Образ жизни
- Питание
- Вторичные половые признаки

От природы:
- У женщин
  - Деторождение
  - Живут на 10 лет дольше
  - Разное устройство мозга
- У мужчин:
  - Интеллект
  - Рост(выше на 10 см)

4 соц. отличия:
1. Что придумал социум: мужчины правили миром. Мораль: древняя женщина была очень тихой-кроткой: иначе мужчина лишит ее еды.
   5 факторов которые испортили идею:
   1. Контрацепция
   2. Увеличилась продолжительность жизни женщин (теперь есть бабушки)
   3. Искусственное питание 
   4. В 1880 8 марта женщины начали класть рельсы (завоевали право на работу).
   5. Разрешенные аборты
   6. Государство поддерживает материнство
   7. Появились детские дошкольные учреждения
2. Мужчины ориентированы на результат, а женщина на процесс
   Доказательство: Все начинается в детстве, девочка играет в куклы (магазин, дочки-матери) Девочки при помощи этих игр отрабатывают диалоги, 
   
   у мальчиков же войнушки (разбойники, спортивные соревнования, конструкторские игры) Результативные игры
   
   Во взрослой жизни мужчина ненавидит одновременные дела, женщина справляется лучше с этой задачей, 
   мужчине трудно переключиться на другое дело.
   
   Пример: Мама приготовила обед, позвенела колокольчиком и зовет кушать: мужская часть квартиры (я сейчас доделаю и приду) — мама в шоке.
   !! У мужчин от этого зависит самооценка 
3. Мужчины агрессивней.?
   Мужчины убивают в 10 раз больше (статистика убийств).
   
   Есть другая статистика: 
   
   Женщины пытаются в 8 раз чаше
   !! Мужчины: Нападают физически или умственно; Женщины: Задеть за живое
4. Мужчины сексуальнее
   1. Имеется в виду сексуальная активность. (Тестостерон делает мужчину полигамным) Полигамность — возможность вступать в связи с разными женщинами.

   2. У мужчин есть программа распространения своей породы

   3. Мужчинам легче в случайную половую связь

   4. У мужчин глобально раньше первый половой опыт

   Есть такая шутка: 
   
   Мужчине надо ответить на два вопроса для вступления в половую связь: ГДЕ и КОГДА. 
   
   Женщине надо ответить на один вопрос: ПОЧЕМУ?


** Типичные жизненные ситуации
1. Женщины ведут себя как матери: Она переживает за молодого человека, заботится о нем
2. Девушка это органайзер — все убирает, складывает, поправляет (Все на своих местах)
   - У мужчины падает жизненная компетентность из-за заботы и органайзерства его девушки (Личная секретарша).
   - Через 5 лет такого общения у мужчины включится кнопка секс-табу.
     - Усугубляет положение рождение ребенка  Классическая вещь: Вопрос Где же наша мама? Давай найдем маму
       Они (женщины) копируют свою мать. — мужчины этому не сопротивляются, таких нет. 
       Женщина хочет незаменимой для своего молодого человека (Без нее он жить не сможет). 
       Она ему даже говорит одну фразу: “Что бы ты без меня делал?”
3. Женщина жалуется (рассказывает о проблеме, ругается) — монолог заканчивается фразой “Я не знаю что делать”.
   - Мужчина предлагает варианты решения (любые), она ему отвечает: Ты ничего не понимаешь!
     Страшная ситуация: Ты тупой. ТЫ МЕНЯ вообще не понимаешь.
     Как себя надо было вести, что это было? У женщины упала самооценка (самооценка зависит от комплиментов и любви). Или можно спросить: Что ты будешь делать? (У тебя уже есть решение-план?)
     Мужчины ненавидят. Есть три степени: 
     1. Когда они неправы
     2. Когда об этом знает женщина
     3. Когда женщина узнает об этом раньше. 
     Решение: Поговорить со своей девушкой: На будущее, можно я всегда буду контролировать ситуацию? Не нужно делать это за меня
4. Женщины неправильно реагируют на комплименты. 
   
   Трагедия в том, что с детства ее приучают быть скромной. 
   
   Лучшие варианты: Я знаю, Я рада что вам понравилось. 
   
   Мужчины обожают уверенных женщин. 
   
   Обидная сторона: Есть очень красивые-умные девушки, но они слишком скромничают.

Послесловие (Опыты Стэнли Милграма)
Собирают людей, Тема эксперимента: Боль на память
1 Серия: В первой серии нет тока, есть актеры // Остановит ли человек с карточкой эксперимент?
>> Влияет авторитет, тока нет.
<< Что если люди = монстры.

2 Серия: Актер теперь мазохист, а авторитет хочет прекратить эксперимент

3 Серия: Стало два профессора (Демон и Ангел) // Решение принимает сам человек
Со злым профессором согласились МУЖЧИНЫ (они хотели результата), а с добрым согласились ЖЕНЩИНЫ (Кайфуют от процесса).

* Откуда берутся дети с ОВЗ?

Три причины:
1. Пренентальные
   - Вирусы (Самое распространённое)

      Вирусы вылечить невозможно — только приглушить на время, иммунная система может их укротить.
      Например, вирус краснухи ⇒ 100% вероятность родится глухим

      !!! Классическая беременность длится 40 недель. (Аборт можно делать до 12 недель).  
   
      С 28-ой недели плод может выжить. 
   
      С 12 по 28 неделю, если застал вирус краснухи — делается аборт только по показаниям.

   - Инфекции 
     Можно победить антибиотиками

     !!! Проблема в том, что лекарство должно быть с точным действием (быть антидотом).

     &%#@
     1. Нельзя парить ноги во время беременности

     2. Нельзя поднимать руки кверху: начинается родовая деятельность

     3. Нельзя резко бросать курить (без некотина в молоке ребенок будет истерично плакать)
2. Натальные
   - Шкала АПГАР: 10 баллов ставят только человеку, которого полностью обследовали.
     
     Здоровый ребенок: 8-9 баллов Розовый, сморщенный ребенок, или если сразу закричал,
     
     Также после успешной проверки орального рефлекса.
     
     Если в 7 месяцев лежит головой вниз — очень хорошая вещь, 
     8 месяцев: попой к низу — показание к кесареву сечению.

** Кесарево сечение
На западе приветствуют Кесарево сечение:
+ облегчение страданий для мамы
+ не прохождение через родовые пути

В России не приветствуют это, «пробивать путь головой» должен обязательно. Но если ягодичное предлежание или если у матери несколько плодов ⇒ Кесарево сечение

Чутка хуже это желтый цвет ребенка.

Все оттенки синего это самое страшное — кислород не поступал достаточно в организм

Если маме оперировали глаза и на хрусталик — ей нельзя рожать, иначе хрусталик отслоится.

Если были проблемы со слуховым нервом, то рожать не рекомендуется

Если женщина рожает в 40+ — Кесарево сечение

Узкий таз мамы — также показание.

!!! Резус-фактор: есть некоторые клетки и антигерои.
Если резус не совпадает у плода и мамы: проблемы с зачатием, 
такая пара сможет забеременеть только один раз.

После родов: главный фактор — как ребенок ест и как он срыгивает/не срыгивает. 
Если он сразу срыгивает — непереносимость молока либо это несовершенство органов пищеварения.

** Наблюдения
В месяц поднимает голову, в три месяца начинает улыбаться. 
В шесть месяцев он сел, также появился первый зуб.

На учет в консультацию надо встать до 9 недели: 
с 9 по 12 недели ей делают генетический анализ (ДНК) — то есть точно знают родится даун или нет.

** Какие бывают ОВЗ?

1 гр. — Тифло-проблемы: Слабовидящие-слепые -  Для них придумали азбуку брайля, сегодня для них придумано огромное количество аудиофайлов.

2 гр. — Сурдо-проблемы: Слабослышащие-глухие - Для них общение с помощью языка жестов, субтитры

3 гр. — ДЦП (Детский церебральный паралич)

4 гр. — Речевые проблемы: Дизграфия, дизкалькулия, дисслалия 
