#+STARTUP: nofold
** Протокол IPv 6

Протокол **IPv6** разработан в качестве преемника IPv4. IPv6 описан в RFC.

Адреса IPv6 имеют длину 128 бит. Обычный адрес IPv6 состоит из двух логических частей префикс и индефикатор интерфейса

Префикс - это часть отведённая под индефикатор.

Адреса IPv6 записываются в виде восьми групп по четыре шестнадцатеричные цифры, где каждая группа по четыре шестнадцатеричные цифры, где каждая разделяется двоетоием.

#+BEGIN_SRC shell
route print
#+END_SRC

* Организация подсетей

Разделение на подсети - процедура сегментирования сетей на сетевые пространства меньшего размера(подсети)

Большие сети необходимо сегментировать на подсети меньшего размера, создавая меньшие группы устройств и служб для следующих целей:
- Контроль трафика
- Снижение общего объёма сетевого трафика и повышение производительности сети.

Обмен данными между подсетями:
- Для обмена требуется маршрутизатор
- Интерфейсы должны иметь IPv4-адреса узла
- Устройства в сети и подсети изпольуют интерфейс маршрутизатора, подключённого их к локальной сети.

Достоинства:
1. Использовать различных сетевых архитектур
2. Ограничение максимального количества узлов в сегменте
3. Ум

При планировании подсетей необходимо учитывать два фактора:
1. требуемое количество подсетей
$$ C = 2 ^ m $$
m - количество бит, на которую нужно удлинить исходную маску.
2. - требуемое количество узлов, пригодных для использования.

$$ Y = 2 ^ n - 2 $$
n - количество бит, используемых в адресе применения новой маски

На основании иходного адреса сети, исходной маски и новой маски перебором битовых комбинаций в позиции тех бит...


164.96.240.0/22 на 6 подсетей

255.255.252.0

m = 3
L = 22 + 3 = 25
255.255.255.128


| 255.255.255.128 | 11111111.10000000 |
|   255.255.255.0 | 11111111.00000000 |
| 255.255.254.128 | 11111110.10000000 |
| 255.255.253.128 | 11111101.10000000 |
| 255.255.255.128 | 11111111.10000000 |

