#+STARTUP: nofold
** Протокол IPv 6

Протокол **IPv6** разработан в качестве преемника IPv4. IPv6 описан в RFC.

Адреса IPv6 имеют длину 128 бит. Обычный адрес IPv6 состоит из двух логических частей префикс и индефикатор интерфейса

Префикс - это часть отведённая под индефикатор.

Адреса IPv6 записываются в виде восьми групп по четыре шестнадцатеричные цифры, где каждая группа по четыре шестнадцатеричные цифры, где каждая разделяется двоетоием.

#+BEGIN_SRC shell
route print
#+END_SRC

* Организация подсетей

Разделение на подсети - процедура сегментирования сетей на сетевые пространства меньшего размера(подсети)

Большие сети необходимо сегментировать на подсети меньшего размера, создавая меньшие группы устройств и служб для следующих целей:
- Контроль трафика
- Снижение общего объёма сетевого трафика и повышение производительности сети.

Обмен данными между подсетями:
- Для обмена требуется маршрутизатор
- Интерфейсы должны иметь IPv4-адреса узла
- Устройства в сети и подсети изпольуют интерфейс маршрутизатора, подключённого их к локальной сети.


